
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vitiqschibbontjwhiim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpdGlxc2NoaWJib250andoaWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTI4NzksImV4cCI6MjA2NTQ4ODg3OX0.eVoqvjIUUI0eJ01LUomMLCAIAjsmOj0dI_Fz0-_wplw";

console.log('🔧 Configuração do Supabase:');
console.log('URL:', SUPABASE_URL);
console.log('Key (primeiros 50 chars):', SUPABASE_PUBLISHABLE_KEY.substring(0, 50) + '...');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false
  },
  global: {
    headers: {
      'X-Client-Info': 'lovable-project'
    }
  }
});

// Teste básico de conectividade
supabase.from('properties').select('count', { count: 'exact', head: true })
  .then(({ error, count }) => {
    if (error) {
      console.error('❌ Erro na inicialização do Supabase:', error);
    } else {
      console.log('✅ Supabase inicializado com sucesso. Propriedades encontradas:', count);
    }
  });
